### ISSUE TITLE
win下安装报错

### ISSUE THREAD

**Issue by livingbody** [PaddleCV-SIG/EISeg#36]
```
(p2) PS H:\EISeg> python -m eiseg
AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\Users\livingbody\miniconda3\envs\p2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\Users\livingbody\miniconda3\envs\p2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "H:\EISeg\eiseg\__main__.py", line 4, in <module>
    main()
  File "H:\EISeg\eiseg\run.py", line 21, in main
    window = APP_EISeg()  # 创建对象
  File "H:\EISeg\eiseg\app.py", line 50, in __init__
    self.setupUi(self)
  File "H:\EISeg\eiseg\ui.py", line 256, in setupUi
    QtCore.QMetaObject.connectSlotsByName(MainWindow)
SystemError: <built-in function connectSlotsByName> returned a result with an error set
```

**Comment by geoyee** [comment]
> ```
> (p2) PS H:\EISeg> python -m eiseg
> AttributeError: __getattribute__
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "F:\Users\livingbody\miniconda3\envs\p2\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "F:\Users\livingbody\miniconda3\envs\p2\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "H:\EISeg\eiseg\__main__.py", line 4, in <module>
>     main()
>   File "H:\EISeg\eiseg\run.py", line 21, in main
>     window = APP_EISeg()  # 创建对象
>   File "H:\EISeg\eiseg\app.py", line 50, in __init__
>     self.setupUi(self)
>   File "H:\EISeg\eiseg\ui.py", line 256, in setupUi
>     QtCore.QMetaObject.connectSlotsByName(MainWindow)
> SystemError: <built-in function connectSlotsByName> returned a result with an error set
> ```

收到，感谢提交，正在检查，暂时没收到这相关问题的反馈

**Comment by geoyee** [comment]
> ```
> (p2) PS H:\EISeg> python -m eiseg
> AttributeError: __getattribute__
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "F:\Users\livingbody\miniconda3\envs\p2\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "F:\Users\livingbody\miniconda3\envs\p2\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "H:\EISeg\eiseg\__main__.py", line 4, in <module>
>     main()
>   File "H:\EISeg\eiseg\run.py", line 21, in main
>     window = APP_EISeg()  # 创建对象
>   File "H:\EISeg\eiseg\app.py", line 50, in __init__
>     self.setupUi(self)
>   File "H:\EISeg\eiseg\ui.py", line 256, in setupUi
>     QtCore.QMetaObject.connectSlotsByName(MainWindow)
> SystemError: <built-in function connectSlotsByName> returned a result with an error set
> ```

@livingbody 请尝试升级PYQT5到5.13以上试试，这可能会解决这个问题
